<?php  if(isset($_SESSION["admin"])){ ?>

<!DOCTYPE HTML>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">

    <head>
        <title>Instituto de Informatica Thomas Alva Edison</title>
        <meta http-equiv="refresh" content="1000" />
        <meta name="description" content="Instituto De Informatica Thomas Alva Edison" />
        <meta name="keywords" content="iitae, informatica, diseño, word, excel, acces, corel draw, php" />
        <meta http-equiv="content-type" content="text/html; charset=utf-8" />
        
        
        <link rel="stylesheet" href="<?php echo Conectar::ruta();?>script/css/estilo.css" type="text/css" />
          
          
          <link rel="stylesheet" type="text/css" href="<?php echo Conectar::ruta();?>script/css/style.css" />
            <script type="text/javascript" src="<?php echo Conectar::ruta();?>script/js/jquery.min.js" ></script>
            <script type="text/javascript" src="<?php echo Conectar::ruta();?>script/js/jquery-ui.min.js" ></script>
            <script type="text/javascript">
            	$(document).ready(function(){
            		$("#featured > ul").tabs({fx:{opacity: "toggle"}}).tabs("rotate", 7000, true);
            	});
            </script>
        
                <!--[if lt IE 9]>
                    <script>
                    var e = ("abbr,article,aside,audio,canvas,datalist,details," +
                    "figure,footer,header,hgroup,mark,menu,meter,nav,output," +
                    "progress,section,time,video").split(',');
                    for (var i = 0; i < e.length; i++) {
                    document.createElement(e[i]);
                    }
                    </script>
               <![endif]-->
        
    </head>
    
    <body>
        <div id="principal">
            <section>
                 <header>
                    <?php include("header2.phtml"); ?>
                 </header>
                  
                  <nav>
                    <?php  $menu=1; include("menu2.phtml");?>
                  </nav>
                  
                  <section id="intro"> 
                  
                         <aside id="asideizquierdoad">

                            <h5 id="tituloesiz">&nbsp;Ultimas Pulicaci&oacute;nes</h5>
                                 <div id="contiz">
                                    sin noticias para este dia
                                 </div>

                     </aside>
                       </aside>
                       
                       <article id="articlecentroad">
                         <div id="culumnaiz">
                            <h5 id="tituloes">&nbsp;Ahora mismo</h5>
                              
                                    <div id="culumnaiz1">&nbsp;Contenido<br />
                                        <div class="textocontenido">
                                            &nbsp;1 Entrada
                                        </div>
                                    
                                    </div>
                                    
                                    <div id="culumnaiz2">&nbsp;Comentarios<br />
                                        <div class="textocontenido">
                                            &nbsp;1 Comentario<br />
                                            &nbsp;1 Aprobado<br />
                                        </div>
                                    </div>
                               
                         </div>
                         
   
                       </article>
                   
                  </section>
            </section>
        
        </div>
        <footer>
            <?php
                include("footer.phtml");
             ?>
        </footer>
        
        
    </body>
</html>
<?php } else{ header("location:".Conectar::ruta()."c-home/"); }?>
