<?php  if(isset($_SESSION["admin"]) or $_SESSION["nom_se"]){ ?>

<!DOCTYPE HTML>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">

    <head>
        <title>Instituto de Informatica Thomas Alva Edison</title>
        <meta http-equiv="refresh" content="1000" />
        <meta name="description" content="Instituto De Informatica Thomas Alva Edison" />
        <meta name="keywords" content="iitae, informatica, diseño, word, excel, acces, corel draw, php" />
        <meta http-equiv="content-type" content="text/html; charset=utf-8" />
        
        
        <link rel="stylesheet" href="<?php echo Conectar::ruta();?>script/css/estilo.css" type="text/css" />
          
          
          <link rel="stylesheet" type="text/css" href="<?php echo Conectar::ruta();?>script/css/style.css" />
          
          <script type="text/javascript" language="javascript" src="<?php echo Conectar::ruta();?>script/js/webcam.js"></script>
          
          <script type="text/javascript" language="javascript" src="<?php echo Conectar::ruta();?>script/ajax/funciones.js"></script>
            
        
        <link href="<?php echo Conectar::ruta();?>script/css/calendario.css" type="text/css" rel="stylesheet">
        <script src="<?php echo Conectar::ruta();?>script/js/calendar.js" type="text/javascript"></script>
        <script src="<?php echo Conectar::ruta();?>script/js/calendar-es.js" type="text/javascript"></script>
        <script src="<?php echo Conectar::ruta();?>script/js/calendar-setup.js" type="text/javascript"></script>
        
                <!--validacion-->
                <script type="text/javascript" src="<?php echo Conectar::ruta();?>script/js/validacion/jquery_1.4.js"></script>
                <script type="text/javascript" src="<?php echo Conectar::ruta();?>script/js/validacion/jquery_validate.js"></script>
                
                <script type="text/javascript">
                $(function(){
                	$('#ra').validate({
                		rules: {
                		'nombre': 'required',
                		'ap': 'required',
                        'sexo': 'required',
                        'edad': 'required',
                        'curp': 'required',
                        'nacademico': 'required',
                        'padre': 'required',
                        'obser': 'required',
                		'tele': { required: true, number: true },
                        'calle': 'required',
                       	'numero': { required: true, number: true },
                        'colo': 'required',
                        'estado': 'required',
                        'muni': 'required',
                        'id_pro': 'required',
                        'gpo': 'required',
                		'email': { required: true, email: true },
                		'tipo_identidad': 'required',
                		'deportes[]': { required: true, minlength: 1 }
                		},
                		messages: {
                		'nombre': '<h5>Debe ingresar el nombre</h5>',
                		'ap': '<h5>Debe ingresar el apellido</h5>',
                        'sexo': '<h5>Seleccione el Sexo</h5>',
                        'edad': '<h5>Seleccione la Edad</h5>',
                        'curp': '<h5>Ingrese la curp</h5>',
                        'nacademico': '<h5>Ingrese nivel academico</h5>',
                        'obser': '<h5>Ingrese Alguna observacion</h5>',
                        'padre': '<h5>Ingrese nivel academico</h5>',
                		'tele': { required: '<h5>Debe ingresar el numero de Telefono<h5>', number: '<h5>Debe ingresar un numero<h5>' },
               		    'calle': '<h5>Ingrese El nombre de la calle</h5>',
                        'numero': { required: '<h5>Debe ingresar el numero de la calle<h5>', number: '<h5>Debe ingresar un numero<h5>' },
                        'colo': '<h5>Ingrese El poblado o coloni</h5>',
                        'estado': '<h5>Ingrese El estado</h5>',
                        'muni': '<h5>Ingrese El estado</h5>',
                        'id_pro': '<h5>Seleccione el promotor</h5>',
                        'gpo': '<h5>Seleccione el grupo</h5>',
                        'email': { required: 'Debe ingresar un correo electrónico', email: 'Debe ingresar el correo electrónico con el formato correcto. Por ejemplo: u@localhost.com' },
                		'tipo_identidad': 'Debe ingresar el número de documento',
                		'deportes[]': 'Debe seleccionar mínimo un deporte'
                		},
                		debug: true,
                		/*errorElement: 'div',*/
                		//errorContainer: $('#errores'),
                		submitHandler: function(form){
                		    alert('El formulario ha sido validado correctamente!');
                			form.submit();
                		}
                	});
                });
                </script>
               <!--fin de validacion-->
        
    </head>
    
    <body>
        <div id="principal">
            <section>
                 <header>
                    <?php
                    if(isset($_SESSION["admin"])){ include("header2.phtml");  }else{ include("headersecretaria.phtml");  }
                      ?>
                 </header>
                  
                  <nav>
                    <?php 
                    if(isset($_SESSION["admin"])){ $menu=3; include("menu2.phtml");  }else{ $menu=1; include("menu_secretaria.phtml");  }
                      ?>
                  </nav>
                  
                  <section id="intro"> 
                  
                   <?php if($v==0){ ?>
                      <aside id="asideizquierdoad1">
                            <h5 id="tituloesiz">&nbsp;Estatus Alumnos</h5>
                                 <div id="contiz1">
                                    <a href="<?php echo Conectar::ruta(); ?>c-alumnos/v-101101101101101101101101101101101/">
                                    <img src="<?php echo Conectar::ruta();?>images/iconos_sistema/add_user.png" border="0" alt="Usuario" title="Rgistrar Alumno" />
                                    </a>
                                         <br />
                                    <a href="<?php echo Conectar::ruta(); ?>c-alumnos/v-2202202202202202202202202202202202/">
                                    <img src="<?php echo Conectar::ruta();?>images/iconos_sistema/send.png" border="0" alt="Usuario" width="48" height="48" title="Consulta de Alumno" />
                                    </a>
                                 </div>

                     </aside>
                  
                  <?php } ?>
                  
                  <?php if($v!=0){ ?>
                         <aside id="asideizquierdoad">
                            <h5 id="tituloesiz">&nbsp;Estatus Alumnos</h5>
                                 <div id="contiz">
                                    <a href="<?php echo Conectar::ruta(); ?>c-alumnos/v-101101101101101101101101101101101/">
                                    <img src="<?php echo Conectar::ruta();?>/images/iconos_sistema/add_user.png" border="0" alt="maestro" title="Rgistrar Alumno" />
                                    </a>
                                    <br />
                                    <a href="<?php echo Conectar::ruta(); ?>c-alumnos/v-2202202202202202202202202202202202/">
                                    <img src="<?php echo Conectar::ruta();?>images/iconos_sistema/send.png" border="0" alt="Usuario" width="48" height="48" title="Consulta de Alumno" />
                                    </a>
                                 </div>

                     </aside>
                     <?php } ?>
                     
                      <?php if($v==0){ ?> 
                       <article id="articlecentroad1">
                         <div id="culumnacentromaestro">
                            <h5 id="tituloes">Sesion de fotos para los alumnos registrados.</h5>
                              
                              <div id="centro1">
                                        <table width="800">
                                        <?php if($con_al_ava!=null){   ?>
                                            <tr>
                                                <th>Matricula</th><th>Nombre</th><th>Apellidos</th><th>Sexo</th><th>Edad</th><th>Tutor</th><th>Curp</th><th align="center">Tomar Foto</th>
                                            </tr>
                                            <?php for($d=0; $d<sizeof($con_al_ava); $d++){ ?>
                                            <tr>
                                                <td><?php echo $con_al_ava[$d]["matricula"]; ?></td><td><?php echo $con_al_ava[$d]["nombre_alum"]; ?></td><td><?php echo $con_al_ava[$d]["apellidos_al"]; ?></td><td><?php echo $con_al_ava[$d]["sexo_al"]; ?></td><td><?php echo $con_al_ava[$d]["edad_al"]; ?></td><td><?php echo $con_al_ava[$d]["tutor_al"]; ?></td> <td><?php echo $con_al_ava[$d]["curp_al"]; ?></td>
                                                <td align="center">
                                                    <a href="<?php echo Conectar::ruta(); ?>c-alumnos/e-1/v-<?php echo $con_al_ava[$d]["cve_alum"]; ?>/">
                                                    <img src="<?php echo Conectar::ruta();?>images/iconos_sistema/video_chat.png" border="0" alt="Tomar Foto" title="Tomar foto" />
                                                    </a>                                                                                                   
                                                </td>
                                            </tr>
                                            
                                            <?php } }else { ?>
                                            <tr>
                                                <td align="center">
                                                  No Alumnos para sesion de fotos
                                                </td>
                                            </tr>
                                            <?php }  ?>
                                        </table>
                                   <h5 id="tituloes">Lista de los &uacute;ltimos 5 Alumnos registrados</h5>
                                   <table  width="800">
                                             <tr>
                                                <th>Matricula</th><th>Nombre</th><th>Apellidos</th><th>Sexo</th><th>Edad</th><th>Tutor</th><th>Curp</th><th align="center">Ver m&aacute;s</th>
                                            </tr>
                                            <?php for($f=0; $f<sizeof($con_ul_5); $f++){ ?>
                                            <tr>
                                                <td><?php echo $con_ul_5[$f]["matricula"]; ?></td><td><?php echo $con_ul_5[$f]["nombre_alum"]; ?></td><td><?php echo $con_ul_5[$f]["apellidos_al"]; ?></td><td><?php echo $con_ul_5[$f]["sexo_al"]; ?></td><td><?php echo $con_ul_5[$f]["edad_al"]; ?></td><td><?php echo $con_ul_5[$f]["tutor_al"]; ?></td> <td><?php echo $con_ul_5[$f]["curp_al"]; ?></td>
                                                <td align="center">
                                                    <a href="<?php echo Conectar::ruta(); ?>c-alumnos/e-2/v-<?php echo $con_ul_5[$f]["cve_alum"]; ?>/">
                                                    <img src="<?php echo Conectar::ruta();?>images/iconos_sistema/ver_mas.jpg" border="0" alt="Tomar Foto" title="ver mas" width="32" height="32" />
                                                    </a>                                                                                                   
                                                </td>
                                            </tr>
                                            <?php } ?>
                                            
                                   </table>  
                                   
                                    </div>
                                    
                                    
                         </div>
                         
                       </article>
                   <?php } ?>
                     
                      <?php if($v==101101101101101101101101101101101){ ?> 
                       <article id="articlecentroad">
                         <div id="culumnacentromaestro">
                            <h4 id="tituloes" align="center">MODULO REGISTRAR ALUMNO</h4>
                              
                            <div id="centro">
                            <form  id="ra" name="ra" method="POST" action="">
                              <table width="670" align="center">
                                <tr>
                                    <td>Fecha. <input type="text" name="fecha" value="<?php echo $fecha_actual = date("Y-m-d");  ?>" readonly="" /></td>
                                    <td>Semana. <input type="text" name="semana" value="<?php echo date('W')+1;?>" readonly="" /></td>
                                    <td>
                                    <?php  
                                    $fecha_actual = date("Y"); $fecha=$fecha_actual-2000; 
                                    if($con_matricula!=null)
                                    {
                                        for($b=0;$b<sizeof($con_matricula); $b++)
                                        {
                                            $m=$con_matricula[$b]["cve_alum"]+1; 
                                        }
                                        if($m<10){$matri="0".$m;}else{ $matri=$m;}
                                    }else
                                    {
                                        $matri="01";
                                    }
                                    ?>
                                    Matricula. <input type="text" name="matricula" value="<?php echo $f=$fecha."E".$matri;?>" readonly="" />
                                    </td>
                                </tr>
                              </table>
                              <table align="center" width="670">
                                <tr>
                                    <td colspan="3" class="tituloes" align="center"> <h5> DATOS DEL ASPIRANTE</h5></td>
                                </tr>
                                <tr>
                                    <td>Nombre: <input type="text" id="nombre" name="nombre" /></td><td colspan="2">Apellidos: <input type="text" id="ap" name="ap" size="50" /> </td>
                                </tr>
                                <tr>
                                    <td>Sexo: <select id="sexo" name="sexo"><option value="">Seleccione</option><option value="Masulino">Masculino</option><option value="Femenino">Femenino</option></select></td>
                                    <td>Edad: <select name="edad" id="edad"><option value="">0</option> <?php for($i=10;$i<70; $i++){ ?> <option value="<?php echo $i; ?>"><?php echo $i; ?></option> <?php } ?></select>A&ntilde;os</td>
                                    <td>Curp: <input type="text" name="curp" id="curp" size="30" /></td>
                                </tr>
                                <tr>
                                    <td colspan="3">Nivel Acad&eacute;mico: <input type="text" id="nacademico" name="nacademico" size="38" /></td>
                                </tr>
                                <tr>
                                    <td colspan="2">Padre o Tutor: <input type="text" name="padre" id="padre" size="41" /></td><td>Telefono: <input type="text" name="tele" id="tele" /></td>
                                </tr>
                                <tr>
                                    <td colspan="3">Observaciones: <input type="text" name="obser" id="obser" size="88" /></td>
                                </tr>
                                <tr>
                                    <td colspan="3" class="tituloes" align="center"> <h5> DOMICILIO</h5></td>
                                </tr>
                                <tr>
                                    <td colspan="2">Calle: <input type="text" name="calle" id="calle" size="50" /></td><td>N&uacute;mero: <input type="text" name="numero" id="numero" size="20" /></td>
                                </tr>
                                <tr>
                                    <td colspan="3">Colonia / Poblado: <input type="text" name="colo" id="colo" size="37" />
                                </tr>
                                <tr>
                                    <td colspan="2">Estado: <input type="text" name="estado" id="estado" size="48" /></h5></td><td><h5>Municipio: <input type="text" name="muni" id="muni" size="20" /></td>
                                </tr>
                                <tr>
                                    <td colspan="3" class="tituloes" align="center"><h5>DATOS GENERALES</h5></td>
                                </tr>
                                <tr>
                                    <td align="center"><h5>Especialidad:</h5></td><td align="center"><h5>Promotor</h5></td><td align="center"><h5>Grupo:</h5></td>
                                </tr>
                                 <tr>
                                    <td align="center">Inform&aacute;tica</td>
                                    <td align="center">
                                    <select name="id_pro" id="id_pro">
                                        <option value="">-Seleccione-</option>
                                        <?php for($c=0;$c<sizeof($con_pro); $c++){  ?>
                                        <option value="<?php echo $con_pro[$c]["cve_usu"];  ?>"><?php echo $con_pro[$c]["nombre_usu"]; echo " "; echo $con_pro[$c]["apellidos_usu"];  ?></option>
                                        <?php } ?>
                                    </select>                            
                                    </td>
                                    <td align="center">
                                    <select name="gpo" id="gpo" onchange="from(document.ra.gpo.value,'cve','http://localhost/iitae/gpo.php')"> 
                                        <option value="">Seleccione</option>
                                        <?php for($a=0; $a<sizeof($con_gpodis); $a++){  ?>
                                            <option value="<?php echo $con_gpodis[$a]["cve_grupo"]; ?>" title="<?php echo $con_gpodis[$a]["nombre_maes"]; echo " "; echo $con_gpodis[$a]["apellido_maes"];  ?>"><?php echo $con_gpodis[$a]["nombre_grupo"]; ?></option>
                                        <?php } ?> 
                                    </select>
                                    </td>
                                </tr>
                                </table>
                                
                                <div id="cve"></div>
                                 <table width="670" align="center">
                                <tr>
                                    <td colspan="3" class="tituloes" align="center"><h5>DOCUMENTOS ENTREGADOS</h5></td>
                                </tr>
                                <tr>
                                    <td align="center"><h5>Acta de Nacimiento: </h5>
                                    <input type="radio" name="an" value="n" checked="" />no <input type="radio" name="an" value="s" /> Si
                                    </td><td align="center"><h5>Constancia de Estudios:</h5>
                                    <input type="radio" name="ce" value="n" checked="" />no <input type="radio" name="ce" value="s" /> Si
                                    </td><td align="center"><h5>Fotos:</h5>
                                    <input type="radio" name="f" value="n" checked="" />no <input type="radio" name="f" value="s" /> Si
                                    </td>
                                </tr>
                                <tr>
                                    <td colspan="3" class="tituloes" align="center"><h5>Cuenta del Alumno</h5></td>
                                </tr>
                                <tr>
                                <td>Login: <input type="text" name="login" value="<?php echo $f; ?>" readonly=""/></td>
                                <td></td>
                                <td>Contrase&ntilde;a: <input type="text" name="pass" value="0000" readonly="" /></td>
                                </tr>
                                <tr>
                                <td colspan="3">
                                
                                <input type="submit" value="Guardar Registro" />
                                <input type="hidden" name="registroa" />
                                </td></tr>
                              </table>
                              </form>
                            </div>
                                    
                                    
                         </div>
                         
                       </article>
                   <?php } ?>

                   
                   
                    <?php if($v==2202202202202202202202202202202202){ ?> 
                                           
                       <article id="articlecentroad">
                         <div id="culumnacentromaestro">
                            <h5 id="tituloes">Consulta Espesifica De Alumnos</h5>
                              
                                    <div id="centro">
                                    <br />
                                    <form method="POST" action="" name="alsecretaria">
                                        <table align="center">
                                            <tr style="background: silver;">
                                                <td align="center" colspan="2" style="color: black; font-weight: bold;">Ingrese Datos Para su Consulta</td>
                                            </tr>
                                            <tr>
                                                <td>Nombre:&nbsp;<input type="text" name="nombre" /> &nbsp;&nbsp;&nbsp;
                                                Apellidos:&nbsp;<input type="text" name="aps" />
                                                </td>
                                            </tr>
                                            <tr>
                                                 <td>
                                                 <input type="hidden" name="consulta_es" />
                                                 <input type="submit" value="Consultar" />
                                                 </td>
                                            </tr>
                                        </table>
                                     </form>
                                     <?php 
                                       if(isset($co_es) and $co_es==1){
                                        ?>
                                        <br />
                                        <table width="670" align="center">
                                            <tr style="background: silver;">
                                                <td align="center" colspan="7" style="color: black; font-weight: bold;">Registros Encontrados</td>
                                            </tr>
                                            <tr>
                                                <th>Nombre</th><th>Apellidos</th><th>Direccion</th><th>Curp</th><th>Estatus</th><th>Asistencia</th><th>Acciones</th>
                                            </tr>
                                            <?php for($i=0; $i<sizeof($consul_es); $i++){ ?>
                                            <tr>
                                                <td><?php echo $consul_es[$i]["nombre_alum"]; ?></td><td><?php echo $consul_es[$i]["apellidos_al"]; ?></td><td><?php echo $consul_es[$i]["col_al"]; ?></td><td><?php echo $consul_es[$i]["curp_al"]; ?></td><td><?php if($consul_es[$i]["status_al"]==1){ echo "Activo"; }else{ echo "Desactivo"; } ?></td><td><?php if($consul_es[$i]["asistencia"]==1){ echo "Activo"; }else{ echo "Desactivo"; } ?></td>
                                                
                                                
                                                <td>
                                                    <a href="<?php echo Conectar::ruta(); ?>c-alumnos/e-2/v-<?php echo $consul_es[$i]["cve_alum"]; ?>/">
                                                  <img src="<?php echo Conectar::ruta();?>images/iconos_sistema/ver_mas.jpg" border="0" alt="ver mas" width="35" height="35" title="Ver Mas" />
                                                 </a>&nbsp;
                                                    
                                                 
                                                 <?php if($consul_es[$i]["status_al"]==1){ ?>
                                                 <a href="<?php echo Conectar::ruta(); ?>c-alumnos/e-3/v-<?php echo $consul_es[$i]["cve_alum"]; ?>/">
                                                 <img src="<?php echo Conectar::ruta();?>images/iconos_sistema/remove_user.png" border="0" alt="Editar" title="Eliminar alumno"  />
                                                </a>&nbsp;
                                                 
                                                 <?php }else{ ?>
                                                 
                                                 <a href="<?php echo Conectar::ruta(); ?>c-alumnos/e-3/v-<?php echo $consul_es[$i]["cve_alum"]; ?>/">
                                                  <img src="<?php echo Conectar::ruta();?>images/iconos_sistema/asignar.png" border="0" alt="Editar" title="Activar Alumno"  />
                                                </a>&nbsp;
                                                 
                                                 <?php } ?>     
                                                </td>    
                                            </tr>
                                            <?php } ?>
                                        </table>
                                        
                                        <?php
                                        
                                       }
                                     ?>       
                                    
                                    </div>
                                    
                                    
                         </div>
                         
                       </article>
                   <?php } ?>
                   
                   
                   <?php if(isset($e) and $e==1){ ?> 
                       <article id="articlecentroad">
                         <div id="culumnacentromaestro">
                            <h5 id="tituloes">Tomar Foto a Maestro</h5>
                              
                                    <div id="centro">
                                    <br />
                                        <table align="center">
                                            <tr style="background: silver;">
                                                <td align="center" colspan="2" style="color: black; font-weight: bold;">Datos Personales</td>
                                            </tr>
                                            <tr>
                                                <td>
                                                
                                                	<!-- Configure a few settings -->
        	<script language="JavaScript">
        		webcam.set_api_url('http://localhost/iitae/script/foto_alumnos/test.php?id=<?php echo $v; ?>');
        		webcam.set_quality( 90 ); // JPEG quality (1 - 100)
        		webcam.set_shutter_sound( true ); // play shutter click sound
        	</script>
        	
        	<!-- Next, write the movie to the page at 320x240 -->
        	<script language="JavaScript">
        		document.write( webcam.get_html(320, 240) );
        	</script>
        	
        	<!-- Some buttons for controlling things -->
        	<br/><br>
        	<form>
        
            <a href="javascript:void(0);" onclick="take_snapshot()" title="Tomar Fotografia">
            <img src="<?php echo Conectar::ruta();?>images/iconos_sistema/webcam.jpg" border="0" width="50" height="50" />
            </a>
             	</form>
        	
        	
        	<!-- Code to handle the server response (see test.php) -->
        	<script language="JavaScript">
        		webcam.set_hook( 'onComplete', 'my_completion_handler' );
        		
        		function take_snapshot() {
        			// take snapshot and upload to server
        			document.getElementById('upload_results').innerHTML = '<h4>Guardando Foto...</h4>';
        			webcam.snap();
        		}
        		
        		function my_completion_handler(msg)
        		 {
        			window.location="http://localhost/iitae/c-alumnos/";	
        		}
        	</script>
                                                
                                                </td>
                                                  <td width="50">&nbsp;</td>
                                                    <td valign="top">
                                    		<div id="upload_results" style="background-color: #00FF40;"></div>
                                    	</td>
                                            </tr>
                                        </table>
                                       
                                    
                                    </div>
                                    
                                    
                         </div>
                         
                       </article>
                   <?php } ?>
                   
                   
                    <?php if(isset($e) and $e==2){ ?> 
                       <article id="articlecentroad">
                         <div id="culumnacentromaestro">
                            <h4 id="tituloes" align="center">MODULO CONSULTAR ALUMNO</h4>
                              
                            <div id="centro">
                            <form name="ra" method="POST" action="">
                              <table width="670" align="center">
                                <tr>
                                    <td>
                                    Fecha de Registro <input type="text" name="fecha" value="<?php echo $con_es_al[0]["fecha"];  ?>" readonly="" size="8" />
                                    <br /><br />
                                    Semana De registro. <input type="text" name="semana" value="<?php echo $con_es_al[0]["semana"];?>" readonly="" size="2" />
                                    <br /><br />
                                    Matricula. <input type="text" name="matricula" value="<?php echo $con_es_al[0]["matricula"];?>" readonly="" />
                                    </td>
                                    <td colspan="2">
                                   <img src="<?php echo Conectar::ruta();?>script/foto_alumnos/avatar/<?php echo$con_es_al[0]["avatar_al"]; ?>" border="0" width="110" height="100" /> 
                                    </td>
                                </tr>
                              </table>
                              <table align="center" width="670">
                                <tr>
                                    <td colspan="3" class="tituloes" align="center"> <h5> DATOS DEL ASPIRANTE</h5></td>
                                </tr>
                                <tr>
                                    <td>Nombre: <input type="text" name="nombre" value="<?php echo $con_es_al[0]["nombre_alum"];?>"readonly="" /></td>
                                    <td colspan="2">Apellidos: <input type="text" name="ap" size="50" value="<?php echo $con_es_al[0]["apellidos_al"];?>" readonly="" /> </td>
                                </tr>
                                <tr>
                                    <td>Sexo: <input name="sexo" value="<?php echo $con_es_al[0]["sexo_al"];;?>" readonly="" /> </td>
                                    <td>Edad: <input type="text" name="edad" value="<?php echo $con_es_al[0]["edad_al"];?>" size="1" readonly=""/> A&ntilde;os </td>
                                    <td>Curp: <input type="text" name="curp" value="<?php echo $con_es_al[0]["curp_al"];?>" readonly="" size="30" /></td>
                                </tr>
                                <tr>
                                    <td colspan="3">Nivel Acad&eacute;mico: <input type="text" name="nacademico" size="38" readonly="" value="<?php echo $con_es_al[0]["nacademico_al"];?>" /></td>
                                </tr>
                                <tr>
                                    <td colspan="2">Padre o Tutor: <input type="text" name="padre" size="41" value="<?php echo $con_es_al[0]["tutor_al"];?>" readonly="" /></td><td>Telefono: <input type="text" name="tele"  value="<?php echo $con_es_al[0]["tel_al"];?>" /></td>
                                </tr>
                                <tr>
                                    <td colspan="3">Observaciones: <input type="text" name="obser"  size="88" value="<?php echo $con_es_al[0]["obser_al"];?>" /></td>
                                </tr>
                                <tr>
                                    <td colspan="3" class="tituloes" align="center"> <h5> DOMICILIO</h5></td>
                                </tr>
                                <tr>
                                    <td colspan="2">Calle: <input type="text" name="calle" size="50" value="<?php echo $con_es_al[0]["calle_al"];?>"  /></td>
                                    <td>N&uacute;mero: <input type="text" name="numero" size="20" value="<?php echo $con_es_al[0]["num_al"];?>"  /></td>
                                </tr>
                                <tr>
                                    <td colspan="3">Colonia / Poblado: <input type="text" name="colo" size="37" value="<?php echo $con_es_al[0]["col_al"];?>" />
                                </tr>
                                <tr>
                                    <td colspan="2">Estado: <input type="text" name="estado" size="48" value="<?php echo $con_es_al[0]["estado_al"];?>" /></h5></td>
                                    <td><h5>Municipio: <input type="text" name="muni" size="20" value="<?php echo $con_es_al[0]["muni_al"];?>" /></td>
                                </tr>
                                <tr>
                                    <td colspan="3" class="tituloes" align="center"><h5>DATOS GENERALES</h5></td>
                                </tr>
                                <tr>
                                    <td align="center"><h5>Especialidad:</h5></td><td align="center"><h5>Promotor</h5></td><td align="center"><h5>Clave del Grupo:</h5></td>
                                </tr>
                                 <tr>
                                    <td align="center">Inform&aacute;tica</td>
                                    <td align="center">
                                    <input type="text" name="pro" readonly="" value="<?php $p=$con_es_al[0]["cve_usu"]; $con_nom_pro=$oalumno->consulta_nom_pro($p); echo $con_nom_pro[0]["nombre_usu"]; echo " "; echo $con_nom_pro[0]["apellidos_usu"];  ?>" readonly="" />                           
                                    </td>
                                    <td align="center">
                                    <input type="text" name="gpo" readonly="" value="<?php echo $_GET["id2"]=$con_es_al[0]["cve_grupo"]; $valor=1;   ?>" readonly="" size="2" />                           
                                    
                                    </td>
                                </tr>
                                </table>
                                
                                <div id="cve">
                                <?php  include_once("gpo.php"); ?>
                                </div>
                                 <table width="670" align="center">
                                <tr>
                                    <td colspan="3" class="tituloes" align="center"><h5>DOCUMENTOS ENTREGADOS</h5></td>
                                </tr>
                                <tr>
                                    <td align="center"><h5>Acta de Nacimiento: </h5>
                                    <?php if($con_es_al[0]["acn_al"]=="n"){?>  
                                    <input type="radio" name="an" value="n"  checked="" />no 
                                    <?php }  ?>
                                    <?php if($con_es_al[0]["acn_al"]=="s"){?> 
                                    <input type="radio" name="an" value="s" checked="" /> Si
                                    <?php }  ?>
                                    </td>
                                    <td align="center"><h5>Constancia de Estudios:</h5>
                                    <?php if($con_es_al[0]["cone"]=="n"){?>  
                                    <input type="radio" name="ce" value="n" checked="" />no 
                                    <?php }  ?>
                                    <?php if($con_es_al[0]["cone"]=="s"){?> 
                                    <input type="radio" name="ce" value="s" checked="" /> Si
                                    <?php }  ?>
                                    </td>
                                    <td align="center"><h5>Fotos:</h5>
                                    <?php if($con_es_al[0]["fto"]=="n"){?> 
                                    <input type="radio" name="f" value="n" checked="" />no
                                    <?php }  ?>
                                    <?php if($con_es_al[0]["fto"]=="s"){?> 
                                     <input type="radio" name="f" value="s" /> Si
                                     <?php }  ?>
                                    </td>
                                </tr>
                                <tr>
                                    <td colspan="3" class="tituloes" align="center"><h5>Cuenta del Alumno</h5></td>
                                </tr>
                                <tr>
                                <td>Login: <input type="text" name="login" value="<?php echo $con_es_al[0]["matricula"];?>" readonly=""/></td>
                                <td></td>
                                <td>Contrase&ntilde;a: <input type="password" name="pass" value="0000" readonly="" /></td>
                                </tr>
                                <tr>
                                <td colspan="3">
                                
                                <input type="submit" value="Actualizar Registro" />
                                <input type="hidden" name="actualizara" />
                                <input type="hidden" name="cve_a" value="<?php echo $con_es_al[0]["cve_alum"];?>" />
                                </td></tr>
                              </table>
                              </form>
                            </div>
                                    
                                    
                         </div>
                         
                       </article>
                   <?php } ?>
                   
                   <?php if(isset($e) and $e==3){ ?> 
                       <article id="articlecentroad">
                         <div id="culumnacentromaestro">
                            <h4 id="tituloes" align="center">MODULO ELIMINAR ALUMNO</h4>
                              
                            <div id="centro">
                            <form name="ra" method="POST" action="">
                              <table width="670" align="center">
                                <tr>
                                    <td>
                                    Fecha de Registro <input type="text" name="fecha" value="<?php echo $con_es_al[0]["fecha"];  ?>" readonly="" size="8" />
                                    <br /><br />
                                    Semana De registro. <input type="text" name="semana" value="<?php echo $con_es_al[0]["semana"];?>" readonly="" size="2" />
                                    <br /><br />
                                    Matricula. <input type="text" name="matricula" value="<?php echo $con_es_al[0]["matricula"];?>" readonly="" />
                                    </td>
                                    <td colspan="2">
                                   <img src="<?php echo Conectar::ruta();?>script/foto_alumnos/avatar/<?php echo$con_es_al[0]["avatar_al"]; ?>" border="0" width="110" height="100" /> 
                                    </td>
                                </tr>
                              </table>
                              <table align="center" width="670">
                                <tr>
                                    <td colspan="3" class="tituloes" align="center"> <h5> DATOS DEL ASPIRANTE</h5></td>
                                </tr>
                                <tr>
                                    <td>Nombre: <input type="text" name="nombre" value="<?php echo $con_es_al[0]["nombre_alum"];?>" /></td>
                                    <td colspan="2">Apellidos: <input type="text" name="ap" size="50" value="<?php echo $con_es_al[0]["apellidos_al"];?>" readonly="" /> </td>
                                </tr>
                                <tr>
                                    <td>Sexo: <input name="sexo" value="<?php echo $con_es_al[0]["sexo_al"];;?>" readonly="" /> </td>
                                    <td>Edad: <input type="text" name="edad" value="<?php echo $con_es_al[0]["edad_al"];?>" size="1" readonly=""/> A&ntilde;os </td>
                                    <td>Curp: <input type="text" name="curp" value="<?php echo $con_es_al[0]["curp_al"];?>" readonly="" size="30" /></td>
                                </tr>
                                <tr>
                                    <td colspan="3">Nivel Acad&eacute;mico: <input type="text" name="nacademico" size="38" readonly="" value="<?php echo $con_es_al[0]["nacademico_al"];?>" /></td>
                                </tr>
                                <tr>
                                    <td colspan="2">Padre o Tutor: <input type="text" name="padre" size="41" value="<?php echo $con_es_al[0]["tutor_al"];?>" readonly="" /></td><td>Telefono: <input type="text" name="tele" readonly="" value="<?php echo $con_es_al[0]["tel_al"];?>" /></td>
                                </tr>
                                <tr>
                                    <td colspan="3">Observaciones: <input type="text" name="obser"  size="88" readonly="" value="<?php echo $con_es_al[0]["obser_al"];?>" /></td>
                                </tr>
                                </table>
                                 <table width="670" align="center">
                                <tr>
                                    <td colspan="3" class="tituloes" align="center"><h5>Estatus del Alumno </h5> <?php if($con_es_al[0]["status_al"]==1){?> <h5 style="color: green;"> Activo  </h5> <?php }else{?> <h5 style="color: red;"> Desactivado  </h5> <?php } ?></td>
                                </tr>
                                <tr>
                                <td colspan="3">
                                Activar<input type="radio" name="e" value="1"/> Dasactivar <input type="radio" name="e" value="0" />
                                
                                </td>
                                </tr>
                                <tr>
                                <td colspan="3">
                                
                                <input type="submit" value="Guardar Registro" />
                                <input type="hidden" name="cve_al" value="<?php echo $v;?>" />
                                <input type="hidden" name="elia" />
                                </td></tr>
                              </table>
                              </form>
                            </div>
                                    
                                    
                         </div>
                         
                       </article>
                   <?php } ?>
                   
                   
                   
                  </section>
            </section>
        
        </div>
       <footer>
            <?php
                include("footer.phtml");
             ?>
        </footer>
        
        
    </body>
</html>
<?php } else{ header("location:".Conectar::ruta()."c-home/"); }?>
