
                  <div id="header">
                        <div id="logo">
                          <img src="<?php echo Conectar::ruta();?>images/logo/logo.png" border="0" alt="logo" title="logo" />
                        </div>
                    
                        <div id="sloganprincipal">
                            <div id="slogan1"><img src="<?php echo Conectar::ruta();?>images/logo/slogan.png" border="0" alt="logo" title="logo" /></div>
                            <div id="slogan2"><img src="<?php echo Conectar::ruta();?>images/logo/slogan2.png" border="0" alt="logo" title="logo" /></div>
                        </div>
                        
                        <div id="redessociales">
                            <div id="redessociales1"><h5>B i e n v e n i d o &nbsp;&nbsp;  al&nbsp;&nbsp;   S i s t e m a ...</h5>
                           <?php if(isset($_SESSION["nom_se"])){ echo $_SESSION["nom_se"]; }?>
                            </div>
                            <div id="redessociales2">
                           <h4> <?php  echo Conectar::fecha(); ?> </h4> 
                            
                            </div>
                            <div id="redessociales3"> <h5>Vista Secretaria</h5></div>
                        </div>
                    
                    </div>