
                  <div id="header">
                        <div id="logo">
                          <img src="<?php echo Conectar::ruta();?>/images/logo/logo.png" border="0" alt="logo" title="logo" />
                        </div>
                    
                        <div id="sloganprincipal">
                            <div id="slogan1"><img src="<?php echo Conectar::ruta();?>images/logo/slogan.png" border="0" alt="logo" title="logo" /></div>
                            <div id="slogan2"><img src="<?php echo Conectar::ruta();?>images/logo/slogan2.png" border="0" alt="logo" title="logo" /></div>
                        </div>
                        
                        <div id="redessociales">
                            <div id="redessociales1"><h5>Validez Oficial REG. &nbsp;S.E.P.&nbsp; 27PBTO1522 </h5>
                            <img src="<?php echo Conectar::ruta();?>images/logo/logosep.png" border="0" alt="logo de la sep" title="logo sep" />
                            <img src="<?php echo Conectar::ruta();?>images/logo/logo2.png" border="0" alt="logo de iitae" title="logo de la escuela IITAE" />
                            </div>
                            <div id="redessociales2">
                            <a href="#"><img src="<?php echo Conectar::ruta();?>images/iconossociales/facebook.png" border="0" alt="facebook" title="facebook" /></a>
                            <a href="#"><img src="<?php echo Conectar::ruta();?>images/iconossociales/twitter.png" border="0" alt="twitter" title="twitter" /></a>
                            <a href="#"><img src="<?php echo Conectar::ruta();?>images/iconossociales/yahoo.png" border="0" alt="yahoo" title="yahoo" /></a>
                            <a href="#"><img src="<?php echo Conectar::ruta();?>images/iconossociales/rss.png" border="0" alt="rss" title="rss" /></a>
                            <a href="#"><img src="<?php echo Conectar::ruta();?>images/iconossociales/youtube.png" border="0" alt="youtube" title="youtube" /></a>
                            
                            
                            
                            </div>
                            <div id="redessociales3"> <h5>Llama al 1234567891 <br /> O escribenos a iitae@homtail.com</h5></div>
                        </div>
                    
                    </div>