<!DOCTYPE HTML>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">

    <head>
        <title>Instituto de Informatica Thomas Alva Edison</title>
        <meta http-equiv="refresh" content="1000" />
        <meta name="description" content="Instituto De Informatica Thomas Alva Edison" />
        <meta name="keywords" content="iitae, informatica, diseño, word, excel, acces, corel draw, php" />
        <meta http-equiv="content-type" content="text/html; charset=utf-8" />
        
        
        <link rel="stylesheet" href="<?php echo Conectar::ruta();?>script/css/estilo.css" type="text/css" />
          
          
          <link rel="stylesheet" type="text/css" href="<?php echo Conectar::ruta();?>script/css/style.css" />
            <script type="text/javascript" src="<?php echo Conectar::ruta();?>script/js/jquery.min.js" ></script>
            <script type="text/javascript" src="<?php echo Conectar::ruta();?>script/js/jquery-ui.min.js" ></script>
            <script type="text/javascript">
            	$(document).ready(function(){
            		$("#featured > ul").tabs({fx:{opacity: "toggle"}}).tabs("rotate", 7000, true);
            	});
            </script>
        
                <!--[if lt IE 9]>
                    <script>
                    var e = ("abbr,article,aside,audio,canvas,datalist,details," +
                    "figure,footer,header,hgroup,mark,menu,meter,nav,output," +
                    "progress,section,time,video").split(',');
                    for (var i = 0; i < e.length; i++) {
                    document.createElement(e[i]);
                    }
                    </script>
               <![endif]-->
        
    </head>
    
    <body>
        <div id="principal">
            <section>
                 <header>
                    <?php include("header.phtml"); ?>
                 </header>
                  
                  <nav>
                    <?php $menu=1;  include("menu.phtml"); ?>
                  </nav>
                  
                  <section id="intro"> 
                  
                         <aside id="asideizquierdo">

<h3 align="center">Promociones</h3>
                         <div align="center">
                         <img src="<?php echo Conectar::ruta();?>images/img_index/anuncio.png" border="0" alt="facebook" title="facebook" />
                         <img src="<?php echo Conectar::ruta();?>images/img_index/anuncio2.png" border="0" alt="facebook" title="facebook" />
                         
                        <!--
<iframe width="270" height="260" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com/maps/ms?msa=0&msid=216683750034574090921.0004c90a4755fe837a290&ie=UTF8&t=m&f=d&daddr=Instituto+de+Informatica+Thomas+Alva+Edison+%4017.757821,-92.594254&ll=17.759231,-92.59552&spn=0.014305,0.013733&z=15&output=embed"></iframe>
                     
-->
</div>

                     </aside>
                       </aside>
                       
                       <article id="articlecentro">
                         <h3 align="left">&nbsp;Conoce nuestras Areas de estudios</h3>
                         
                            <!-- -->
                            		<div id="featured" >
                          		  
                                      <ul class="ui-tabs-nav">
                            	        <li class="ui-tabs-nav-item ui-tabs-selected" id="nav-fragment-1"><a href="#fragment-1"><img src="<?php echo Conectar::ruta();?>images/img_index/image1-small.jpg" alt="" /><span>Laboratorios Climatizados</span></a></li>
                            	        <li class="ui-tabs-nav-item" id="nav-fragment-2"><a href="#fragment-2"><img src="<?php echo Conectar::ruta();?>images/img_index/image2-small.jpg" alt="" /><span>Salones para Teorias</span></a></li>
                            	        <li class="ui-tabs-nav-item" id="nav-fragment-3"><a href="#fragment-3"><img src="<?php echo Conectar::ruta();?>images/img_index/image3-small.jpg" alt="" /><span>Aulas con las Comodidaes para estudiar</span></a></li>
                            	        <li class="ui-tabs-nav-item" id="nav-fragment-4"><a href="#fragment-4"><img src="<?php echo Conectar::ruta();?>images/img_index/image4-small.jpg" alt="" /><span>Todos los equipos Con windows 7</span></a></li>
                            	       
                                      </ul>
                           
                            	    <!-- First Content -->
                            	    <div id="fragment-1" class="ui-tabs-panel" style="">
                            			<img src="<?php echo Conectar::ruta();?>/images/img_index/image1.jpg" alt="" />
                            			 <div class="info" >
                            				<h2><a href="#" >Laboratorios Climatizados</a></h2>
                            				<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla tincidunt condimentum lacus. Pellentesque ut diam....<a href="#" >read more</a></p>
                            			 </div>
                            	    </div>
                            
                	                <!-- Second Content -->
                            	    <div id="fragment-2" class="ui-tabs-panel ui-tabs-hide" style="">
                            			<img src="<?php echo Conectar::ruta();?>/images/img_index/image2.jpg" alt="" />
                            			 <div class="info" >
                            				<h2><a href="#" >Salones para Teorias</a></h2>
                            				<p>Vestibulum leo quam, accumsan nec porttitor a, euismod ac tortor. Sed ipsum lorem, sagittis non egestas id, suscipit....<a href="#" >read more</a></p>
                            			 </div>
                            	    </div>
                            
                            	    <!-- Third Content -->
                            	    <div id="fragment-3" class="ui-tabs-panel ui-tabs-hide" style="">
                            			<img src="<?php echo Conectar::ruta();?>/images/img_index/image3.jpg" alt="" />
                            			 <div class="info" >
                            				<h2><a href="#" >Aulas con las Comodidaes para estudiar</a></h2>
                            				<p>liquam erat volutpat. Proin id volutpat nisi. Nulla facilisi. Curabitur facilisis sollicitudin ornare....<a href="#" >read more</a></p>
                            	         </div>
                            	    </div>
                            
                            	    <!-- Fourth Content -->
                            	    <div id="fragment-4" class="ui-tabs-panel ui-tabs-hide" style="">
                            			<img src="<?php echo Conectar::ruta();?>/images/img_index/image4.jpg" alt="" />
                            			 <div class="info" >
                            				<h2><a href="#" >Todos los equipos Con windows 7</a></h2>
                            				<p>Quisque sed orci ut lacus viverra interdum ornare sed est. Donec porta, erat eu pretium luctus, leo augue sodales....<a href="#" >read more</a></p>
                            	         </div>
                          	      </div>
                                    
                                    
                                    <!-- Second Content -->
    	                            
                            
                            		</div>
                           <!-- -->            
                            
                       </article>
                       
                       <article id="articlecentro">
                       <img src="<?php echo Conectar::ruta();?>/images/img_index/aviso.png" border="0" alt="facebook" title="facebook" />
                         
                       </article>
                   
                  </section>
            </section>
        
        </div>
        <footer>
            <?php
                include("footer.phtml");
             ?>
        </footer>
        
        
    </body>
</html>

