<ul>  
                        <li><a href="<?php echo Conectar::ruta();?>c-home/" class="<?php if($menu==1){ echo "botna"; }  ?>">Inicio</a></li>  
                        <li><a href="<?php echo Conectar::ruta();?>c-modulos-especialidad/" class="<?php if($menu==2){ echo "botna"; }  ?>" >M&oacute;dulos de la Especialidad</a></li>  
                        <li><a href="<?php echo Conectar::ruta();?>c-ninos/" class="<?php if($menu==3){ echo "botna"; }  ?>">Computaci&oacute;n Para Ni&ntilde;os</a></li>  
                        <li><a href="<?php echo Conectar::ruta();?>c-ingles/" class="<?php if($menu==4){ echo "botna"; }  ?>">Ingles</a></li>  
                        <li><a href="<?php echo Conectar::ruta();?>c-nosotros/" class="<?php if($menu==5){ echo "botna"; }  ?>">Nosotros</a></li>
                        <li><a href="<?php echo Conectar::ruta();?>c-contacto/" class="<?php if($menu==6){ echo "botna"; }  ?>">Cont&aacute;ctanos</a></li> 
                        <li><a href="<?php echo Conectar::ruta();?>c-login/" class="<?php if($menu==7){ echo "botna"; }  ?>">Login</a></li>  
</ul> 