<ul>  
                        <li><a href="<?php echo Conectar::ruta();?>c-aini/" class="<?php if($menu==1){ echo "botna"; }  ?>">Inicio</a></li>  
                        <li><a href="<?php echo Conectar::ruta();?>c-aini/e-1/" class="<?php if($menu==2){ echo "botna"; }  ?>" >Horario</a></li> 
                        <li><a href="<?php echo Conectar::ruta();?>c-aini/e-2/" class="<?php if($menu==2){ echo "botna"; }  ?>" >Calificaciones</a></li> 
                        <li><a href="<?php echo Conectar::ruta();?>c-aini/e-3/" class="<?php if($menu==2){ echo "botna"; }  ?>" >Pr&aacute;cticas</a></li>
                        <li><a href="<?php echo Conectar::ruta();?>c-aini/e-5/" class="<?php if($menu==2){ echo "botna"; }  ?>" >Lista de Pr&aacute;cticas</a></li>
                        <li><a href="<?php echo Conectar::ruta();?>c-aini/e-4/" class="<?php if($menu==2){ echo "botna"; }  ?>" >Fechas</a></li>
                        <li><a href="<?php echo Conectar::ruta();?>c-cerrar/" class="<?php if($menu==7){ echo "botna"; }  ?>">Cerrar Sesion</a></li>  
</ul> 