<ul>  
                        <li><a href="<?php echo Conectar::ruta();?>c-admin/" class="<?php if($menu==1){ echo "botna"; }  ?>">Inicio</a></li>  
                        <li><a href="<?php echo Conectar::ruta();?>c-maestros/" class="<?php if($menu==2){ echo "botna"; }  ?>" >Maestros</a></li>  
                        <li><a href="<?php echo Conectar::ruta();?>c-alumnos/" class="<?php if($menu==3){ echo "botna"; }  ?>">Alumnos</a></li>  
                        <li><a href="<?php echo Conectar::ruta();?>c-grupos/" class="<?php if($menu==4){ echo "botna"; }  ?>">Grupos</a></li>  
                        <li><a href="<?php echo Conectar::ruta();?>c-secretaria/" class="<?php if($menu==6){ echo "botna"; }  ?>">Personal</a></li>
                         <li><a href="<?php echo Conectar::ruta();?>c-cerrar/" class="<?php if($menu==7){ echo "botna"; }  ?>">Cerrar Sesion</a></li>  
</ul> 