<ul>  
                        <li><a href="<?php echo Conectar::ruta();?>c-mini/" class="<?php if($menu==1){ echo "botna"; }  ?>">Inicio</a></li>  
                        <li><a href="<?php echo Conectar::ruta();?>c-mini/e-1/" class="<?php if($menu==2){ echo "botna"; }  ?>" >Grupos</a></li> 
                        <li><a href="<?php echo Conectar::ruta();?>c-mini/e-2/" class="<?php if($menu==3){ echo "botna"; }  ?>" >Pr&aacute;cticas</a></li>
                        <li><a href="<?php echo Conectar::ruta();?>c-mini/e-3/" class="<?php if($menu==4){ echo "botna"; }  ?>" >Ver Pr&aacute;cticas</a></li>
                        <li><a href="<?php echo Conectar::ruta();?>c-cerrar/" class="<?php if($menu==7){ echo "botna"; }  ?>">Cerrar Sesion</a></li>  
</ul> 