<?php  if(isset($_SESSION["admin"]) or $_SESSION["nom_se"]){ ?>

<!DOCTYPE HTML>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">

    <head>
        <title>Instituto de Informatica Thomas Alva Edison</title>
        <meta http-equiv="refresh" content="1000" />
        <meta name="description" content="Instituto De Informatica Thomas Alva Edison" />
        <meta name="keywords" content="iitae, informatica, diseño, word, excel, acces, corel draw, php" />
        <meta http-equiv="content-type" content="text/html; charset=utf-8" />
        
        
        <link rel="stylesheet" href="<?php echo Conectar::ruta();?>script/css/estilo.css" type="text/css" />
          
          
          <link rel="stylesheet" type="text/css" href="<?php echo Conectar::ruta();?>script/css/style.css" />
          
          	<script type="text/javascript" language="javascript" src="<?php echo Conectar::ruta();?>script/js/webcam.js"></script>
            
        
                <!--[if lt IE 9]>
                    <script>
                    var e = ("abbr,article,aside,audio,canvas,datalist,details," +
                    "figure,footer,header,hgroup,mark,menu,meter,nav,output," +
                    "progress,section,time,video").split(',');
                    for (var i = 0; i < e.length; i++) {
                    document.createElement(e[i]);
                    }
                    </script>
               <![endif]-->
        
    </head>
    
    <body>
        <div id="principal">
            <section>
                 <header>
                    <?php 
                    
                    if(isset($_SESSION["admin"])){ include("header2.phtml");  }else{ include("headersecretaria.phtml");}
                    ?>
                 </header>
                  
                  <nav>
                    <?php  
                    if(isset($_SESSION["admin"])){ $menu=6; include("menu2.phtml");  }else{ $menu=1; include("menu_secretaria.phtml");  }

                    
                    ?>
                  </nav>
                  
                  <section id="intro"> 
                  
                  <?php if($v==0){ ?>
                      <aside id="asideizquierdoad1">
                            <h5 id="tituloesiz">&nbsp;Estatus Usuarios</h5>
                                 <div id="contiz1">
                                    <a href="<?php echo Conectar::ruta(); ?>c-secretaria/v-10901010101010/">
                                    <img src="<?php echo Conectar::ruta();?>images/iconos_sistema/add_user.png" border="0" alt="Usuario" title="Alta de Usuario" />
                                    </a>
                                         <br />
                                    <a href="<?php echo Conectar::ruta(); ?>c-secretaria/v-10901010101011/">
                                    <img src="<?php echo Conectar::ruta();?>images/iconos_sistema/send.png" border="0" alt="Usuario" width="48" height="48" title="Consulta de Usuario" />
                                    </a>
                                 </div>

                     </aside>
                  
                  <?php } ?>
                  <?php if($v!=0){ ?>
                         <aside id="asideizquierdoad">

                            <h5 id="tituloesiz">&nbsp;Estatus Usuarios</h5>
                                 <div id="contiz">
                                    <a href="<?php echo Conectar::ruta(); ?>c-secretaria/v-10901010101010/">
                                    <img src="<?php echo Conectar::ruta();?>/images/iconos_sistema/add_user.png" border="0" alt="maestro" title="Alta de Usuarios" />
                                    </a>
                                    <br />
                                    <a href="<?php echo Conectar::ruta(); ?>c-secretaria/v-10901010101011/">
                                    <img src="<?php echo Conectar::ruta();?>images/iconos_sistema/send.png" border="0" alt="Usuario" width="48" height="48" title="Consulta de Usuario" />
                                    </a>
                                 </div>

                     </aside>
                     <?php } ?>
                       </aside>
                       
                      <?php if($v==0){ ?> 
                       <article id="articlecentroad1">
                         <div id="culumnacentromaestro">
                            <h5 id="tituloes">Usuarios Acuales en Labor</h5>
                              
                                    <div id="centro1">
                                        <table width="800">
                                            <tr>
                                                <th>Nombre</th><th>Apellidos</th><th>Telefono</th><th>Sexo</th><th>Carrera</th><th>Categoria</th><th>Acciones</th>
                                            </tr>
                                            <?php for($i=0; $i<sizeof($consulta_user); $i++){ ?>
                                            <tr>
                                                <td><?php echo $consulta_user[$i]["nombre_usu"]; ?></td><td><?php echo $consulta_user[$i]["apellidos_usu"]; ?></td><td><?php echo $consulta_user[$i]["telefono_usu"]; ?></td><td><?php echo $consulta_user[$i]["sexo_usu"]; ?></td><td><?php echo $consulta_user[$i]["carrera"]; ?></td><td><?php echo $consulta_user[$i]["nombre_cat"]; ?></td>
                                                <td>

                                               <?php 
                                               
                                               $av=$consulta_user[$i]["cve_usu"];
                                               $ava=$secre->consulta_user_avatar($av);
                                               for($x=$i; $x<sizeof($ava); $x++)
                                               {
                                                  $av2=$ava[$x]["cve_usu"];
                                                  if($av2=='')
                                                  {
                                                    ?>
                                                    
                                                    <a href="#">
                                                  <img src="<?php echo Conectar::ruta();?>images/iconos_sistema/remove_user.png" border="0" alt="Eliminar" title="Tome Una Foto A '<?php echo $consulta_user[$i]["nombre_cat"]; ?>' " />
                                                 </a>&nbsp;
                                                 
                                                    <a href="#">
                                                  <img src="<?php echo Conectar::ruta();?>images/iconos_sistema/edit_user.png" border="0" alt="Editar" title="El Usuario <?php echo $consulta_user[$i]["nombre_cat"]; ?> No Tiene Foto, Tomele Una" />
                                                </a>&nbsp;
                                                    
                                                    
                                                <a href="<?php echo Conectar::ruta(); ?>c-secretaria/e-3/v-<?php echo $consulta_user[$i]["cve_usu"]; ?>/">
                                                    <img src="<?php echo Conectar::ruta();?>images/iconos_sistema/video_chat.png" border="1" alt="Tomar Foto" title=" 'Sin foto' Tomar Foto" />
                                                 </a>
                                                    
                                                    <?php
                                                  }else{
                                                    ?>
                                                    <a href="<?php echo Conectar::ruta(); ?>c-secretaria/e-2/v-<?php echo $consulta_user[$i]["cve_usu"]; ?>/">
                                                  <img src="<?php echo Conectar::ruta();?>images/iconos_sistema/remove_user.png" border="0" alt="Eliminar" title="Eliminar '<?php echo $consulta_user[$i]["nombre_cat"]; ?>' " />
                                                 </a>&nbsp;
                                                    <a href="<?php echo Conectar::ruta(); ?>c-secretaria/e-1/v-<?php echo $consulta_user[$i]["cve_usu"]; ?>/">
                                                  <img src="<?php echo Conectar::ruta();?>images/iconos_sistema/edit_user.png" border="0" alt="Editar" title="Ver mas sobre <?php echo $consulta_user[$i]["nombre_cat"]; ?>" />
                                                </a>&nbsp;
                                                    
                                                    <a href="#">
                                                    <img src="<?php echo Conectar::ruta();?>images/iconos_sistema/video_chat.png" border="0" alt="Tomar Foto" title=" 'Error' Usuario con Foto" />
                                                 </a>
                                                    
                                                    <?php
                                                  }
                                               }
                                               
                                               
                                               
                                                 ?>
                                               
                                               
                                                                                                                                                   
                                                </td>
                                            </tr>
                                            <?php } ?>
                                        </table>
                                    
                                    </div>
                                    
                                    
                         </div>
                         
                       </article>
                   <?php } ?>
                   
                   <?php if($v==10901010101010){ ?> 
                       <article id="articlecentroad">
                         <div id="culumnacentromaestro">
                            <h5 id="tituloes">Alta De Secretarias</h5>
                              
                                    <div id="centro">
                                    <br />
                                    <form method="POST" action="" name="alsecretaria">
                                        <table align="center">
                                            <tr style="background: silver;">
                                                <td align="center" colspan="2" style="color: black; font-weight: bold;">Datos Personales</td>
                                            </tr>
                                            <tr>
                                                <td>Folio:&nbsp;&nbsp;&nbsp;<input type="text" name="f" readonly="" value="<?php for($i=0;$i<sizeof($con_fol); $i++){ echo $con_fol[$i]["cve_usu"]+1; }     ?>" />
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>Nombre:&nbsp;<input type="text" name="nombre" /> &nbsp;&nbsp;&nbsp;
                                                Apellidos:&nbsp;<input type="text" name="aps" />
                                                </td>
                                            </tr>
                                             <tr>
                                                <td>Direccion:&nbsp;<input type="text" name="dire" /> &nbsp;&nbsp;&nbsp;
                                                Telefono:&nbsp;<input type="text" name="tel" />
                                                </td>
                                            </tr>
                                             <tr>
                                                <td>Correo Electronico:&nbsp;<input type="text" name="correo" /> &nbsp;&nbsp;&nbsp;
                                                Sexo:&nbsp;<select name="sexo"><option value="Masculino">Masculino</option><option value="Femenino">Femenino</option></select>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>Carrera:&nbsp;<input type="text" name="carrera" /> &nbsp;&nbsp;&nbsp;
                                                 Categoria: &nbsp;<select name="cat">
                                                 <?php  for($i=0; $i<sizeof($ver); $i++){ ?>
                                                 <option value="<?php echo $ver[$i]["cve_cat_user"] ?>"><?php echo $ver[$i]["nombre_cat"] ?></option>
                                                 
                                                  <?php } ?>
                                                </td>
                                            </tr>
                                            <tr style="background: silver;">
                                                <td align="center" colspan="2" style="color: black; font-weight: bold;">Datos Para la Cuenta (Solo Para Secretarias)</td>
                                            </tr>
                                            <tr>
                                                <td>Nombre de la Cuenta:&nbsp;<input type="text" name="login" /> &nbsp;&nbsp;&nbsp;
                                                Contrase&ntilde;a:&nbsp;<input type="password" name="pass" />
                                                </td>
                                            </tr>
                                            <tr>
                                                 <td>
                                                 <input type="hidden" name="als" />
                                                 <input type="submit" value="Guardar Registro" />
                                                 </td>
                                            </tr>
                                        </table>
                                     </form>       
                                    
                                    </div>
                                    
                                    
                         </div>
                         
                       </article>
                   <?php } ?>
                   
                   
                   <?php if($v==10901010101011){ ?> 
                       <article id="articlecentroad">
                         <div id="culumnacentromaestro">
                            <h5 id="tituloes">Alta De Secretarias</h5>
                              
                                    <div id="centro">
                                    <br />
                                    <form method="POST" action="" name="alsecretaria">
                                        <table align="center">
                                            <tr style="background: silver;">
                                                <td align="center" colspan="2" style="color: black; font-weight: bold;">Ingrese Datos Para su Consulta</td>
                                            </tr>
                                            <tr>
                                                <td>Nombre:&nbsp;<input type="text" name="nombre" /> &nbsp;&nbsp;&nbsp;
                                                Apellidos:&nbsp;<input type="text" name="aps" />
                                                </td>
                                            </tr>
                                            <tr>
                                                 <td>
                                                 <input type="hidden" name="consulta_es" />
                                                 <input type="submit" value="Consultar" />
                                                 </td>
                                            </tr>
                                        </table>
                                     </form>
                                     <?php 
                                       if(isset($co_es) and $co_es==1){
                                        ?>
                                        <br />
                                        <table width="680" align="center">
                                            <tr style="background: silver;">
                                                <td align="center" colspan="6" style="color: black; font-weight: bold;">Registros Encontrados</td>
                                            </tr>
                                            <tr>
                                                <th>Nombre</th><th>Apellidos</th><th>Direccion</th><th>Categoria</th><th>Estatus</th><th>Acciones</th>
                                            </tr>
                                            <?php for($i=0; $i<sizeof($consul_es); $i++){ ?>
                                            <tr>
                                                <td><?php echo $consul_es[$i]["nombre_usu"]; ?></td><td><?php echo $consul_es[$i]["apellidos_usu"]; ?></td><td><?php echo $consul_es[$i]["direccion_usu"]; ?></td><td><?php echo $consul_es[$i]["nombre_cat"]; ?></td><td><?php if($consul_es[$i]["status"]==1){ echo "Activo"; }else{ echo "Desactivo"; } ?></td>
                                                
                                                
                                                <td>
                                                 <?php 
                                               
                                               $av=$consul_es[$i]["cve_usu"];
                                               $ava=$secre->consulta_user_avatar($av);
                                               for($x=$i; $x<sizeof($ava); $x++)
                                               {
                                                  $av2=$ava[$x]["cve_usu"];
                                                  if($av2=='')
                                                  {
                                                    ?>
                                                    
                                                    <a href="#">
                                                  <img src="<?php echo Conectar::ruta();?>images/iconos_sistema/remove_user.png" border="0" alt="Eliminar" title="Tome Una Foto A '<?php echo $consul_es[$i]["nombre_cat"]; ?>' " />
                                                 </a>&nbsp;
                                                 
                                                    <a href="#">
                                                  <img src="<?php echo Conectar::ruta();?>images/iconos_sistema/edit_user.png" border="0" alt="Editar" title="El Usuario <?php echo $consul_es[$i]["nombre_cat"]; ?> No Tiene Foto, Tomele Una" />
                                                </a>&nbsp;
                                                    
                                                    
                                                <a href="<?php echo Conectar::ruta(); ?>c-secretaria/e-3/v-<?php echo $consul_es[$i]["cve_usu"]; ?>/">
                                                    <img src="<?php echo Conectar::ruta();?>images/iconos_sistema/video_chat.png" border="1" alt="Tomar Foto" title=" 'Sin foto' Tomar Foto" />
                                                 </a>
                                                    
                                                    <?php
                                                  }else{
                                                    ?>
                                                    <a href="<?php echo Conectar::ruta(); ?>c-secretaria/e-2/v-<?php echo $consul_es[$i]["cve_usu"]; ?>/">
                                                  <img src="<?php echo Conectar::ruta();?>images/iconos_sistema/remove_user.png" border="0" alt="Eliminar" title="Activar o Desactivar '<?php echo $consul_es[$i]["nombre_cat"]; ?>' " />
                                                 </a>&nbsp;
                                                    
                                                    <a href="<?php echo Conectar::ruta(); ?>c-secretaria/e-1/v-<?php echo $consul_es[$i]["cve_usu"]; ?>/">
                                                  <img src="<?php echo Conectar::ruta();?>images/iconos_sistema/edit_user.png" border="0" alt="Editar" title="Ver mas sobre <?php echo $consul_es[$i]["nombre_cat"]; ?>" />
                                                </a>&nbsp;
                                                    
                                                    <a href="#">
                                                    <img src="<?php echo Conectar::ruta();?>images/iconos_sistema/video_chat.png" border="0" alt="Tomar Foto" title=" 'Error' Usuario con Foto" />
                                                 </a>
                                                    
                                                    <?php
                                                  }
                                               }
                                               
                                               
                                               
                                                 ?>
                                                
                                                </td>
                                                
                                                
                                            </tr>
                                            <?php } ?>
                                        </table>
                                        
                                        <?php
                                        
                                       }
                                     ?>       
                                    
                                    </div>
                                    
                                    
                         </div>
                         
                       </article>
                   <?php } ?>
                   
                   
                   <?php if(isset($e) and $e==1){ ?> 
                       <article id="articlecentroad">
                         <div id="culumnacentromaestro">
                            <h5 id="tituloes">Consultas Espesificas de Usuario</h5>
                              
                                    <div id="centro">
                                    <br />
                                    <form method="POST" action="" name="alsecretaria">
                                        <table align="center">
                                            <tr style="background: silver;">
                                                <td align="center" colspan="2" style="color: black; font-weight: bold;">Datos Personales</td>
                                            </tr>
                                            <tr>
                                                <td>
                     <img src="<?php echo Conectar::ruta();?>script/foto_usuarios/avatar/<?php echo $consulta_es[0]["nom_foto_av"]; ?>" border="0" alt="avatar" title="Avatar" width="100" height="80" /></a>             
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>Nombre:&nbsp;<input type="text" name="nombre" readonly="" value="<?php echo $consulta_es[0]["nombre_usu"]; ?>" /> &nbsp;&nbsp;&nbsp;
                                                Apellidos:&nbsp;<input type="text" name="aps" readonly="" size="30" value="<?php echo $consulta_es[0]["apellidos_usu"]; ?>" />
                                                </td>
                                            </tr>
                                             <tr>
                                                <td>Direccion:&nbsp; <input type="text" name="dire" size="67" readonly="" value="<?php echo $consulta_es[0]["direccion_usu"]; ?>" /> &nbsp;&nbsp;&nbsp;
                                                </td>
                                            </tr>
                                             <tr><td>
                                               Telefono:&nbsp;<input type="text" name="tel" readonly="" value="<?php echo $consulta_es[0]["telefono_usu"]; ?>" />
                                                </td>
                                            </tr>
                                             <tr>
                                                <td>Correo Electronico:&nbsp;<input type="text" name="correo" size="30" readonly="" value="<?php echo $consulta_es[0]["correo"]; ?>" /> &nbsp;&nbsp;&nbsp;
                                                Sexo:&nbsp;<input type="text" name="sexo" readonly="" size="13" value="<?php echo $consulta_es[0]["sexo_usu"]; ?>" />                                                </td>
                                            </tr>
                                            <tr>
                                                <td>Carrera:&nbsp;<input type="text" name="carrera" readonly="" value="<?php echo $consulta_es[0]["carrera"]; ?>" /> &nbsp;&nbsp;&nbsp;
                                                 Puesto: &nbsp;<input type="text" name="cat" readonly="" value="<?php echo $consulta_es[0]["nombre_cat"]; ?>" />
                                                </td>
                                            </tr>
                                            <tr>
                                                 <td>
                                                 <input type="hidden" name="als" />
                                                 <input type="submit" value="Guardar Registro" />
                                                 </td>
                                            </tr>
                                        </table>
                                     </form>       
                                    
                                    </div>
                                    
                                    
                         </div>
                         
                       </article>
                   <?php } ?>
                   
                   
                    <?php if(isset($e) and $e==2){ ?> 
                       <article id="articlecentroad">
                         <div id="culumnacentromaestro">
                            <h5 id="tituloes">Eliminacion de Usuario</h5>
                              
                                    <div id="centro">
                                    <br />
                                    <form method="POST" action="" name="alsecretaria">
                                        <table align="center">
                                            <tr style="background: silver;">
                                                <td align="center" colspan="2" style="color: black; font-weight: bold;">Datos Personales</td>
                                            </tr>
                                            <tr>
                                                <td>
                     <img src="<?php echo Conectar::ruta();?>script/foto_usuarios/avatar/<?php echo $consulta_es[0]["nom_foto_av"]; ?>" border="0" alt="avatar" title="Avatar" width="100" height="80" /></a>             
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>Nombre:&nbsp;<input type="text" name="nombre" readonly="" value="<?php echo $consulta_es[0]["nombre_usu"]; ?>" /> &nbsp;&nbsp;&nbsp;
                                                Apellidos:&nbsp;<input type="text" name="aps" readonly="" size="30" value="<?php echo $consulta_es[0]["apellidos_usu"]; ?>" />
                                                </td>
                                            </tr>
                                            
                                             
                                            <tr>
                                                <td> Puesto: &nbsp;<input type="text" name="cat" readonly="" value="<?php echo $consulta_es[0]["nombre_cat"]; ?>" />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                                Estatus <input type="radio" name="es" value="1" checked="" />Activo<input type="radio" name="es" value="0"  />Desactivar
                                                </td>
                                            </tr>
                                            <tr>
                                                 <td>
                                                 <input type="hidden" name="on" />
                                                 <input type="hidden" name="cve" value="<?php echo $v; ?>" />
                                                <input type="submit" value="Guardar Cambios" />
                                                 </td>
                                            </tr>
                                        </table>
                                     </form>       
                                    
                                    </div>
                                    
                                    
                         </div>
                         
                       </article>
                   <?php } ?>
                   
                   
                   <?php if(isset($e) and $e==3){ ?> 
                       <article id="articlecentroad">
                         <div id="culumnacentromaestro">
                            <h5 id="tituloes">Tomar Foto a Secretarias</h5>
                              
                                    <div id="centro">
                                    <br />
                                        <table align="center">
                                            <tr style="background: silver;">
                                                <td align="center" colspan="2" style="color: black; font-weight: bold;">Datos Personales</td>
                                            </tr>
                                            <tr>
                                                <td>
                                                
                                                	<!-- Configure a few settings -->
        	<script language="JavaScript">
        		webcam.set_api_url('http://localhost/iitae/script/foto_usuarios/test.php?id=<?php echo $v; ?>');
        		webcam.set_quality( 90 ); // JPEG quality (1 - 100)
        		webcam.set_shutter_sound( true ); // play shutter click sound
        	</script>
        	
        	<!-- Next, write the movie to the page at 320x240 -->
        	<script language="JavaScript">
        		document.write( webcam.get_html(320, 240) );
        	</script>
        	
        	<!-- Some buttons for controlling things -->
        	<br/><br>
        	<form>
        
            <a href="javascript:void(0);" onclick="take_snapshot()" title="Tomar Fotografia">
            <img src="<?php echo Conectar::ruta();?>images/iconos_sistema/webcam.jpg" border="0" width="50" height="50">
            </a>
             	</form>
        	
        	
        	<!-- Code to handle the server response (see test.php) -->
        	<script language="JavaScript">
        		webcam.set_hook( 'onComplete', 'my_completion_handler' );
        		
        		function take_snapshot() {
        			// take snapshot and upload to server
        			document.getElementById('upload_results').innerHTML = '<h4>Guardando Foto...</h4>';
        			webcam.snap();
        		}
        		
        		function my_completion_handler(msg)
        		 {
        			window.location="http://localhost/iitae/c-secretaria/";	
        		}
        	</script>
                                                
                                                </td>
                                                  <td width=50>&nbsp;</td>
                <td valign=top>
		<div id="upload_results" style="background-color: #00FF40;"></div>
	</td>
                                            </tr>
                                        </table>
                                       
                                    
                                    </div>
                                    
                                    
                         </div>
                         
                       </article>
                   <?php } ?>
                   
                   
                   
                  </section>
            </section>
        
        </div>
       <footer>
            <?php
                include("footer.phtml");
             ?>
        </footer>
        
        
    </body>
</html>
<?php } else{ header("location:".Conectar::ruta()."c-home/"); }?>
